const {test}=require('node:test'),assert=require('node:assert/strict'),ts=require('typescript'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const judge='00000000-0000-4000-8000-000000000001',actor='00000000-0000-4000-8000-000000000002',version='2026-09-21T12:00:00.000Z';
function fixture(){const state={calls:0,denied:false,error:null,data:judge,revalidated:[]};const module={exports:{}};const deps={'zod':require('zod'),'next/navigation':{redirect:url=>{throw Error('REDIRECT '+url);}},'next/cache':{revalidatePath:p=>state.revalidated.push(p)},'../../../lib/users/access':{requireUserManager:async()=>{if(state.denied)throw Error('DENIED');return {id:actor};}},'../../../lib/supabase/server':{createClient:async()=>({rpc:async(name,args)=>{state.calls++;assert.equal(name,'roboscore_delete_judge');assert.equal(args.p_id,judge);assert.equal(args.p_version,version);return {data:state.data,error:state.error};}})}};const code=ts.transpileModule(fs.readFileSync(path.join(__dirname,'../app/admin/usuarios/delete-judge-actions.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,require:n=>deps[n]});return {state,run:(id=judge,v=version,confirmed=true)=>{const form=new FormData();if(confirmed)form.set('confirm','yes');return module.exports.deleteJudge(id,v,{},form);}};}
test('Missing confirmation never reaches database',async()=>{const f=fixture();assert.match((await f.run(judge,version,false)).message,/Confirma/);assert.equal(f.state.calls,0);});
test('Invalid IDs, versions and self-deletion rejected',async()=>{for(const [id,v] of [['bad',version],[judge,'bad'],[actor,version]]){const f=fixture();assert.match((await f.run(id,v)).message,/ficha/);assert.equal(f.state.calls,0);}});
test('Authorization precedes deletion',async()=>{const f=fixture();f.state.denied=true;await assert.rejects(f.run(),{message:'DENIED'});assert.equal(f.state.calls,0);});
test('Database permission and stale-version errors stay visible',async()=>{const f=fixture();f.state.error={code:'40001',message:'Recarga la ficha'};assert.equal((await f.run()).message,'Recarga la ficha');assert.equal(f.state.revalidated.length,0);});
test('Missing migration produces actionable error',async()=>{const f=fixture();f.state.error={code:'PGRST202',message:'internal'};assert.match((await f.run()).message,/Supabase/);});
test('Only confirmed deletion refreshes views and redirects',async()=>{const f=fixture();await assert.rejects(f.run(),{message:'REDIRECT /admin/jueces?resultado=eliminado'});assert.ok(f.state.revalidated.includes('/admin'));assert.ok(f.state.revalidated.includes('/judge'));});
test('Unexpected response is not reported as success',async()=>{const f=fixture();f.state.data=null;assert.match((await f.run()).message,/No pudimos confirmar/);assert.equal(f.state.revalidated.length,0);});
