import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const db=new PGlite(),root=new URL('../',import.meta.url),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb,email_confirmed_at timestamptz,invited_at timestamptz);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;GRANT USAGE ON SCHEMA public,auth TO authenticated;GRANT USAGE ON SCHEMA public TO anon;`);
for(const file of ['tests/fixtures/foundation.sql','supabase/migrations/202609160001_profiles_roles.sql','supabase/migrations/202609200002_event_management.sql','supabase/migrations/202609200004_user_management.sql','supabase/migrations/202609210003_delete_judges.sql','supabase/migrations/202609210003_delete_judges.sql'])await db.exec(await fs.readFile(new URL(file,root),'utf8'));
for(let n=1;n<=6;n++){await db.query('INSERT INTO auth.users VALUES($1,$2,$3,now(),null)',[id(n),`test${n}@example.test`,{}]);await db.query('UPDATE profiles SET role=$1,active=$2,managed_by=$3 WHERE id=$4',[n===1?'SUPER_ADMIN':n<=3||n===6?'ADMIN':'JUDGE',n!==6,n===4?id(2):n===5?id(3):null,id(n)]);}
await db.query("INSERT INTO events(id,name,slug,start_date,end_date,created_by) VALUES($1,'Test','test',now(),now(),$2)",[id(10),id(2)]);await db.query("INSERT INTO event_categories(id,event_id,name) VALUES($1,$2,'Test')",[id(20),id(10)]);await db.query('INSERT INTO judge_assignments(judge_id,event_id,category_id,assigned_by) VALUES($1,$2,$3,$4)',[id(4),id(10),id(20),id(2)]);
async function asUser(n,role='authenticated'){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('SET ROLE '+role);}
const versions=new Map((await db.query('SELECT id,updated_at::text AS v FROM profiles')).rows.map(r=>[r.id,r.v]));
const remove=(n,v=versions.get(id(n)))=>db.query('SELECT roboscore_delete_judge($1,$2)',[id(n),v]);let count=0;const pass=name=>{count++;console.log('PASS '+name);};
await asUser(0,'anon');await assert.rejects(remove(4),{code:'42501'});pass('Anonymous callers denied');
await asUser(4);await assert.rejects(remove(5),{code:'42501'});await asUser(6);await assert.rejects(remove(4),{code:'42501'});pass('Judges and inactive administrators denied');
await asUser(3);await assert.rejects(remove(4),{code:'42501'});pass('An administrator cannot delete another manager’s judge');
await asUser(1);for(const n of [1,2,3])await assert.rejects(remove(n),{code:'42501'});pass('Self, administrator and superadministrator accounts protected');
await asUser(2);await assert.rejects(remove(4,'2000-01-01T00:00:00Z'),{code:'40001'});pass('Stale confirmation cannot delete a changed profile');
await remove(4);let row=(await db.query('SELECT active,deleted_at,deleted_by FROM profiles WHERE id=$1',[id(4)])).rows[0];assert.equal(row.active,false);assert.ok(row.deleted_at);assert.equal(row.deleted_by,id(2));pass('Owner can delete judge with audit timestamp and actor');
await remove(4);const retry=(await db.query('SELECT deleted_at FROM profiles WHERE id=$1',[id(4)])).rows[0];assert.deepEqual(retry.deleted_at,row.deleted_at);pass('Repeated deletion is idempotent');
await db.exec('RESET ROLE');const assignment=(await db.query('SELECT active FROM judge_assignments WHERE judge_id=$1',[id(4)])).rows[0];assert.equal(assignment.active,false);assert.equal((await db.query('SELECT id FROM auth.users WHERE id=$1',[id(4)])).rows.length,1);pass('Assignment history and identity retained; assignments disabled');
const version=(await db.query('SELECT updated_at::text AS v FROM profiles WHERE id=$1',[id(4)])).rows[0].v;
await asUser(2);await assert.rejects(db.query("SELECT roboscore_update_managed_user($1,$2,'Ana','Test','','JUDGE',true)",[id(4),version]),{code:'22023'});pass('Older editing API cannot reactivate deleted judge');
await asUser(1);await remove(5);await assert.rejects(db.query('DELETE FROM profiles WHERE id=$1',[id(5)]),{code:'42501'});assert.equal((await db.query("SELECT id FROM profiles WHERE role='JUDGE' AND deleted_at IS NULL")).rows.length,0);pass('Superadmin can delete any judge; no direct deletion grant');
await db.exec('RESET ROLE');const verification=await db.query(await fs.readFile(new URL('supabase/verify-delete-judges.sql',root),'utf8'));assert.equal(verification.rows.length,4);for(const row of verification.rows)assert.equal(row.passed,true,row.check_name);pass('Four installation checks pass');
await db.close();console.log(`${count} checks passed; no remote accounts changed.`);
