const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
function load(file,dependencies){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,require:n=>n in dependencies?dependencies[n]:require(n),URL,Date});return module.exports;}
const schema=load('lib/events/schema.ts',{});const owner='00000000-0000-4000-8000-000000000001';const id='00000000-0000-4000-8000-000000000010';
function setup(){const rows=new Map();const state={denied:false,calls:0,fail:false};const action=load('app/admin/eventos/actions.ts',{'../../../lib/events/schema':schema,'../../../lib/auth/authorization':{requireAccess:async area=>{assert.equal(area,'admin');if(state.denied)throw Error('DENIED');return {id:owner}}},'next/navigation':{redirect:url=>{throw Error('REDIRECT '+url)}},'next/cache':{revalidatePath:()=>{}},'../../../lib/supabase/server':{createClient:async()=>({from:()=>{
let filters=[],payload;const q={select:()=>q,eq:(k,v)=>{filters.push([k,v]);return q},update:p=>{payload=p;return q},insert:async p=>{state.calls++;if(state.fail)throw Error('network');if(rows.has(p.id))return {error:{code:'23505'}};rows.set(p.id,{...p,updated_at:'2026-09-20T12:00:00.000Z'});return {error:null}},maybeSingle:async()=>{if(state.fail)throw Error('network');const row=[...rows.values()].find(r=>filters.every(([k,v])=>r[k]===v));if(row&&payload){state.calls++;Object.assign(row,payload,{updated_at:'2026-09-20T12:01:00.000Z'})}return {data:row??null,error:null}}};return q;}})}});return {rows,state,save:action.saveEvent};}
function form(overrides={}){const f=new FormData();Object.entries({...schema.emptyValues,name:'Robótica',start_date:'2026-10-01T09:00',end_date:'2026-10-01T18:00',...overrides}).forEach(([k,v])=>{if(k==='public'){if(v)f.set(k,'on')}else f.set(k,v)});return f;}
test('Create derives owner server-side and replay does not duplicate',async()=>{const t=setup();const f=form();f.set('created_by','forged');f.set('role','SUPER_ADMIN');await assert.rejects(t.save(id,null,{},f),{message:`REDIRECT /admin/eventos/${id}?resultado=creado`});await assert.rejects(t.save(id,null,{},f),{message:`REDIRECT /admin/eventos/${id}?resultado=creado`});assert.equal(t.rows.size,1);assert.equal(t.rows.get(id).created_by,owner);assert.equal(t.rows.get(id).start_date,'2026-10-01T14:00:00.000Z');assert.equal(t.rows.get(id).role,undefined)});
test('Invalid dates never reach the database',async()=>{const t=setup();const result=await t.save(id,null,{},form({end_date:'2026-09-01T09:00'}));assert(result.errors.end_date);assert.equal(t.state.calls,0)});
test('Authorization runs before mutation',async()=>{const t=setup();t.state.denied=true;await assert.rejects(t.save(id,null,{},form()),{message:'DENIED'});assert.equal(t.state.calls,0)});
test('Conflicting version preserves data and user inputs',async()=>{const t=setup();t.rows.set(id,{id,updated_at:'2026-09-20T12:01:00.000Z',name:'Newer'});const result=await t.save(id,'2026-09-20T12:00:00.000Z',{},form({name:'Stale'}));assert.match(result.message,/otra sesión/);assert.equal(t.rows.get(id).name,'Newer');assert.equal(result.values.name,'Stale')});
test('Cancellation updates rather than deleting',async()=>{const t=setup();t.rows.set(id,{id,updated_at:'2026-09-20T12:00:00.000Z'});await assert.rejects(t.save(id,'2026-09-20T12:00:00.000Z',{},form({status:'CANCELLED'})),{message:`REDIRECT /admin/eventos/${id}?resultado=guardado`});assert.equal(t.rows.size,1);assert.equal(t.rows.get(id).status,'CANCELLED')});
test('Connection error retains entered values',async()=>{const t=setup();t.state.fail=true;const result=await t.save(id,null,{},form());assert.match(result.message,/conexión/);assert.equal(result.values.name,'Robótica')});
