const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../lib/events/schema.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:mod,exports:mod.exports,require,URL,Date});
const {eventSchema,emptyValues,toPayload,toLocalDate,recordValues}=mod.exports;
const valid={...emptyValues,name:'Competencia',start_date:'2026-10-01T09:00',end_date:'2026-10-01T18:00'};
for(const [label,change] of [['empty name',{name:'   '}],['invalid day',{start_date:'2026-02-30T09:00'}],['invalid hour',{start_date:'2026-10-01T25:00'}],['reversed dates',{end_date:'2026-09-30T10:00'}],['removed registration status',{status:'REGISTRATION'}],['zero capacity',{max_teams:'0'}],['fractional capacity',{max_teams:'1.2'}],['overflow capacity',{max_teams:'2147483648'}],['unsafe URL',{rules_url:'javascript:alert(1)'}],['credentials URL',{logo_url:'https://user:password@example.com/logo.png'}],['unknown status',{status:'PUBLIC'}]])test('Rejects '+label,()=>assert.equal(eventSchema.safeParse({...valid,...change}).success,false));
test('Optional fields and cancellation are accepted',()=>{assert(eventSchema.safeParse(valid).success);assert(eventSchema.safeParse({...valid,status:'CANCELLED'}).success)});
test('Colombia local dates round-trip without browser timezone dependence',()=>{const parsed=eventSchema.parse(valid);const payload=toPayload(parsed);assert.equal(payload.start_date,'2026-10-01T14:00:00.000Z');assert.equal(toLocalDate(payload.start_date),valid.start_date);assert.equal(payload.registration_start,null);assert.equal(payload.max_teams,null)});
test('Nullable database values populate blank inputs',()=>{const values=recordValues({...valid,start_date:'2026-10-01T14:00:00Z',end_date:'2026-10-01T23:00:00Z',max_teams:null,registration_start:null,registration_end:null,description:null});assert.equal(values.description,'');assert.equal(values.max_teams,'');assert.equal(values.start_date,'2026-10-01T09:00')});
test('Legacy event remains editable without enrollment dates',()=>{const values=recordValues({...valid,status:'REGISTRATION',start_date:'2026-10-01T14:00:00Z',end_date:'2026-10-01T23:00:00Z',max_teams:null,registration_start:'2026-09-01T00:00:00Z',registration_end:'2026-09-30T00:00:00Z'});assert.equal(values.status,'DRAFT');assert.equal('registration_start' in values,false);const payload=toPayload(eventSchema.parse(values));assert.equal(payload.registration_start,null);assert.equal(payload.registration_end,null)});
