const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
function load(file,deps={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,URLSearchParams,require:name=>deps[name]??require(name)});return module.exports;}
const {parseInvitationFragment}=load('lib/auth/invitation-link.ts');
test('Default invitation fragment extracts a session without changing it',()=>{const link=parseInvitationFragment('#access_token=test-access&refresh_token=test-refresh&type=invite');assert.equal(link.kind,'session');assert.equal(link.accessToken,'test-access');assert.equal(link.refreshToken,'test-refresh');});
test('Normal anchors and other auth flows are ignored',()=>{for(const hash of ['#resultados','#access_token=test&type=signup','#access_token=test&type=magiclink',''])assert.equal(parseInvitationFragment(hash),null);});
test('Malformed or oversized invitation callbacks become safe errors',()=>{assert.equal(parseInvitationFragment('#type=invite&access_token=only-access').kind,'error');assert.equal(parseInvitationFragment('#type=invite&access_token='+ 'a'.repeat(16001)+'&refresh_token=r').kind,'error');});
test('Provider error descriptions are never echoed into UI',()=>{const link=parseInvitationFragment('#type=invite&error=expired&error_description=private-value');assert.equal(link.kind,'error');assert.ok(!link.message.includes('private-value'));});
function fixture(){const state={sessionError:null,session:{access_token:'mock'},user:{id:'judge-id',invited_at:'2026-09-21T12:00:00Z'},userError:null,active:true,profileError:null,signouts:0,calls:0};const client={auth:{setSession:async()=>{state.calls++;return {data:{session:state.session},error:state.sessionError};},getUser:async()=>({data:{user:state.user},error:state.userError}),signOut:async()=>{state.signouts++;}},from:()=>({select:()=>({eq:(_,id)=>{assert.equal(id,'judge-id');return {single:async()=>({data:{active:state.active},error:state.profileError})};}})})};const action=load('app/auth/invitacion/session-actions.ts',{'next/navigation':{redirect:url=>{throw Error('REDIRECT '+url);}},'../../../lib/supabase/server':{createClient:async remember=>{assert.equal(remember,false);return client;}}});return {state,run:(a='test-access',r='test-refresh',flow='invite')=>action.acceptInvitationSession(a,r,flow,{})};}
test('A verified active invited judge reaches password setup',async()=>{const f=fixture();await assert.rejects(f.run(),{message:'REDIRECT /cuenta/crear-clave'});assert.equal(f.state.signouts,0);});
test('An invalid token pair never reaches Auth',async()=>{const f=fixture();assert.match((await f.run('','')).message,/incompleto/);assert.equal(f.state.calls,0);});
test('Expired sessions are cleared and do not redirect',async()=>{const f=fixture();f.state.sessionError={code:'invalid_token'};assert.match((await f.run()).message,/sesión/);assert.equal(f.state.signouts,1);});
test('A session without a server-verified user cannot continue',async()=>{const f=fixture();f.state.userError={code:'bad_jwt'};assert.match((await f.run()).message,/verificar/);assert.equal(f.state.signouts,1);});
test('Non-invited accounts cannot use the invitation callback',async()=>{const f=fixture();f.state.user.invited_at=null;assert.match((await f.run()).message,/verificar/);assert.equal(f.state.signouts,1);});
test('Inactive and unreadable profiles cannot reach password setup',async()=>{for(const failure of ['active','profileError']){const f=fixture();f.state[failure]=failure==='active'?false:{code:'permission_denied'};assert.match((await f.run()).message,/perfil no está habilitado/);assert.equal(f.state.signouts,1);}});

test('Recovery links extract a session and are marked as recovery',()=>{const link=parseInvitationFragment('#access_token=a&refresh_token=r&type=recovery');assert.equal(link.kind,'session');assert.equal(link.flow,'recovery');assert.equal(parseInvitationFragment('#access_token=a&refresh_token=r&type=invite').flow,'invite');});
test('Recovery errors get their own safe message',()=>{const link=parseInvitationFragment('#type=recovery&error=expired&error_description=private-value');assert.equal(link.kind,'error');assert.match(link.message,/restablecer/i);assert.ok(!link.message.includes('private-value'));});
test('A confirmed judge who never set a password can recover and reach password setup',async()=>{const f=fixture();f.state.user={id:'judge-id',invited_at:'2026-09-21T12:00:00Z',recovery_sent_at:'2026-09-24T12:00:00Z'};await assert.rejects(f.run('test-access','test-refresh','recovery'),{message:'REDIRECT /cuenta/crear-clave'});assert.equal(f.state.signouts,0);});
test('A recovery session needs a provisioning or recovery timestamp',async()=>{const f=fixture();f.state.user={id:'judge-id'};assert.match((await f.run('test-access','test-refresh','recovery')).message,/verificar/);assert.equal(f.state.signouts,1);});
test('Recovery never bypasses the active profile check',async()=>{const f=fixture();f.state.user={id:'judge-id',recovery_sent_at:'2026-09-24T12:00:00Z'};f.state.active=false;assert.match((await f.run('test-access','test-refresh','recovery')).message,/perfil no está habilitado/);assert.equal(f.state.signouts,1);});
