import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const db=new PGlite(),root=new URL('../',import.meta.url),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,raw_user_meta_data jsonb,email_confirmed_at timestamptz,invited_at timestamptz);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;GRANT USAGE ON SCHEMA public,auth TO authenticated;GRANT USAGE ON SCHEMA public TO anon;`);
for(const file of ['tests/fixtures/foundation.sql','supabase/migrations/202609160001_profiles_roles.sql','supabase/migrations/202609200002_event_management.sql','supabase/migrations/202609200003_category_management.sql','supabase/migrations/202609200004_user_management.sql','supabase/migrations/202609210001_teams_scoring.sql','supabase/migrations/202609210002_public_results.sql','supabase/migrations/202609210003_delete_judges.sql','supabase/migrations/202609210004_judge_scoring.sql','supabase/migrations/202609210004_judge_scoring.sql'])await db.exec(await fs.readFile(new URL(file,root),'utf8'));
for(let n=1;n<=6;n++){await db.query('INSERT INTO auth.users VALUES($1,$2,$3,now(),null)',[id(n),`test${n}@example.test`,{}]);await db.query('UPDATE profiles SET role=$1,active=$2,managed_by=$3 WHERE id=$4',[n===1?'SUPER_ADMIN':n<=3?'ADMIN':'JUDGE',n!==6,n>=4?id(n===5?3:2):null,id(n)]);}
for(let n=10;n<=11;n++){await db.query("INSERT INTO events(id,name,slug,start_date,end_date,created_by,status,public) VALUES($1,'Test',$2,now(),now(),$3,'ACTIVE',true)",[id(n),'test-'+n,id(n===10?2:3)]);await db.query("INSERT INTO event_categories(id,event_id,name,status) VALUES($1,$2,'Category','ACTIVE')",[id(n+10),id(n)]);await db.query("INSERT INTO teams(id,event_id,category_id,name,institution,status) VALUES($1,$2,$3,'Team','School','ACTIVE')",[id(n+20),id(n),id(n+10)]);}
async function asUser(n,role='authenticated'){await db.exec('RESET ROLE');await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('SET ROLE '+role);}
const rpc=async(name,args=[])=>{return (await db.query(`SELECT ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) AS result`,args)).rows[0].result;};
const assign=(judge=4,active=true,event=10,category=20)=>rpc('roboscore_assign_judge',[id(event),id(category),id(judge),active]);
let checks=0;const pass=name=>{checks++;console.log('PASS '+name);};
await asUser(2);await rpc('roboscore_configure_scoring',[id(10),id(20),'EXCEL_2026',3]);const challenge=(await db.query('SELECT id FROM event_challenges WHERE category_id=$1 ORDER BY sort_order',[id(20)])).rows[0].id;
const save=(version=null,notes='',team=30,attempt=1,seconds=8.275)=>rpc('roboscore_save_score',[id(10),id(team),challenge,version,attempt,seconds,true,notes]);
await assert.rejects(assign(5),{code:'42501'});await assert.rejects(assign(6),{code:'42501'});await assert.rejects(assign(4,true,11,21),{code:'42501'});await assert.rejects(assign(4,true,10,21),{code:'22023'});pass('Managers cannot assign foreign/inactive judges or mismatched categories');
const assignment=await assign();assert.equal(await assign(),assignment);pass('Assignment is idempotent');
await asUser(4);const home=await rpc('roboscore_judge_home');assert.equal(home.length,1);assert.equal(home[0].category_id,id(20));assert.equal(home[0].teams,1);assert.equal((await rpc('roboscore_judge_category',[id(20)])).teams.length,1);pass('Judge sees assigned category and teams only');
await assert.rejects(rpc('roboscore_judge_category',[id(21)]),{code:'42501'});await assert.rejects(rpc('roboscore_judge_team',[id(31)]),{code:'42501'});await assert.rejects(save(null,'',31),{code:'42501'});await assert.rejects(rpc('roboscore_event_judges',[id(10)]),{code:'42501'});pass('Foreign teams, categories and administrative directory denied');
await assert.rejects(assign(),{code:'42501'});await assert.rejects(rpc('roboscore_configure_scoring',[id(10),id(20),'LEGACY_C',3]),{code:'42501'});pass('Judges cannot assign themselves or change scoring rules');
await save();let team=await rpc('roboscore_judge_team',[id(30)]);assert.equal(team.scores[0].points,161.725);assert.equal(team.scores[0].attempt,1);pass('Assigned judge saves exact Excel score');
await assert.rejects(save(),{code:'40001'});await assert.rejects(save(team.scores[0].updated_at),{code:'22023'});const oldVersion=team.scores[0].updated_at;await save(oldVersion,'Corrección de cronómetro',30,1,10);await assert.rejects(save(oldVersion,'Otra edición'),{code:'40001'});pass('Concurrent edits and corrections require current version and reason');
await db.exec('RESET ROLE');const history=(await db.query('SELECT old_data,new_data,changed_by FROM score_revisions ORDER BY id')).rows;assert.equal(history.length,2);assert.equal(Number(history[1].old_data.points),161.725);assert.equal(Number(history[1].new_data.points),160);assert.equal(history[1].changed_by,id(4));pass('History records judge, old points and correction');
await asUser(0,'anon');assert.equal((await rpc('roboscore_public_results')).teams.find(t=>t.id===id(30)).total,160);await assert.rejects(rpc('roboscore_judge_home'),{code:'42501'});pass('Public totals update; anonymous judge access denied');
await asUser(2);await assign(4,false);await asUser(4);assert.equal((await rpc('roboscore_judge_home')).length,0);await assert.rejects(save(),{code:'42501'});await assert.rejects(rpc('roboscore_judge_team',[id(30)]),{code:'42501'});pass('Revocation blocks already-open forms and future reads');
await asUser(2);await assign();await db.query("UPDATE events SET status='FINISHED' WHERE id=$1",[id(10)]);await asUser(4);team=await rpc('roboscore_judge_team',[id(30)]);await assert.rejects(save(team.scores[0].updated_at,'Closed event'),{code:'22023'});pass('Finished event remains readable but cannot be scored');
await asUser(2);await db.query("UPDATE events SET status='ACTIVE' WHERE id=$1",[id(10)]);await db.exec('RESET ROLE');await db.query("UPDATE event_categories SET status='CLOSED' WHERE id=$1",[id(20)]);await asUser(4);await assert.rejects(save(team.scores[0].updated_at,'Closed category'),{code:'22023'});pass('Closed categories reject scoring');
await db.exec('RESET ROLE');await db.query("UPDATE event_categories SET status='ACTIVE' WHERE id=$1",[id(20)]);await db.query("UPDATE teams SET status='REJECTED' WHERE id=$1",[id(30)]);await asUser(4);await assert.rejects(save(team.scores[0].updated_at,'Withdrawn'),{code:'22023'});pass('Withdrawn teams reject scoring');
await db.exec('RESET ROLE');await db.query("UPDATE teams SET status='ACTIVE' WHERE id=$1",[id(30)]);const version=(await db.query('SELECT updated_at::text AS v FROM profiles WHERE id=$1',[id(4)])).rows[0].v;await asUser(2);await rpc('roboscore_delete_judge',[id(4),version]);await asUser(4);await assert.rejects(save(),{code:'42501'});await assert.rejects(rpc('roboscore_judge_home'),{code:'42501'});pass('Deleted judge cannot use prior assignments or open forms');
await asUser(1);const finalTeam=(await db.query('SELECT updated_at::text AS v FROM team_scores WHERE team_id=$1',[id(30)])).rows[0];await save(finalTeam.v,'Corrección administrativa');assert.equal((await rpc('roboscore_scoring_board',[id(10),id(20)])).teams[0].total,161.725);pass('Administrative scoring remains supported');
await db.exec('RESET ROLE');const verification=await db.query(await fs.readFile(new URL('supabase/verify-judge-scoring.sql',root),'utf8'));assert.equal(verification.rows.length,4);for(const row of verification.rows)assert.equal(row.passed,true,row.check_name);pass('Four installation checks pass');
await db.close();console.log(`${checks} checks passed; no remote data changed.`);
