const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
function load(file,deps={}){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{module,exports:module.exports,console:{error(){}},require:name=>deps[name]??require(name)});return module.exports;}
function fixture(){const state={calls:[],result:{error:null},throwOnSend:false,clientOptions:null};
 const action=load('app/auth/recuperar/actions.ts',{'@supabase/supabase-js':{createClient:(url,key,options)=>{state.clientOptions=options;return {auth:{resetPasswordForEmail:async(email,opts)=>{if(state.throwOnSend)throw Error('network');state.calls.push({email,opts});return state.result;}}};}},'../../../lib/auth/config':{authConfig:()=>({url:'https://x.supabase.co',key:'k'}),authFetch:fetch},'../../../lib/supabase/admin':{invitationConfig:()=>({redirectTo:'https://example.test/auth/invitacion'})}});
 const form=email=>{const data=new FormData();data.set('email',email);return data;};
 return {state,run:email=>action.requestPasswordReset({},form(email))};}
test('A valid email sends the recovery link back to the invitation page and answers neutrally',async()=>{const f=fixture();const result=await f.run('  Dany@Uniminuto.edu.co ');assert.equal(f.state.calls.length,1);assert.equal(f.state.calls[0].email,'Dany@Uniminuto.edu.co');assert.equal(f.state.calls[0].opts.redirectTo,'https://example.test/auth/invitacion');assert.match(result.message,/Si ese correo/);assert.equal(result.error,undefined);});
test('The session comes back in the URL fragment (implicit flow), not a PKCE code',async()=>{const f=fixture();await f.run('a@b.co');assert.equal(f.state.clientOptions.auth.flowType,'implicit');assert.equal(f.state.clientOptions.auth.persistSession,false);});
test('Invalid emails never reach Auth',async()=>{const f=fixture();for(const bad of ['','no-es-correo','a@'])assert.match((await f.run(bad)).error,/correo válido/);assert.equal(f.state.calls.length,0);});
test('Auth failures give a helpful error without saying whether the account exists',async()=>{const f=fixture();f.state.result={error:{name:'AuthApiError',code:'over_email_send_rate_limit',status:429}};assert.match((await f.run('a@b.co')).error,/Espera un minuto/);f.state.result={error:{name:'AuthApiError',code:'unexpected_failure',status:500}};const generic=await f.run('a@b.co');assert.match(generic.error,/unos minutos/);assert.ok(!/no existe|no está registrado/i.test(generic.error));});
test('A network failure is reported without crashing',async()=>{const f=fixture();f.state.throwOnSend=true;assert.match((await f.run('a@b.co')).error,/conectar/);});
