const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');
function load(file,deps={}){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>n in deps?deps[n]:require(n),Intl});return module.exports;}
const schema=load('lib/scoring/schema.ts');
// Exact reference inputs and cached outputs; no team or participant names copied.
const excel=[['CATA!H4',1,8.275,161.725],['CATA!H5',1,12.774,157.226],['CATA!H6',1,25.649,144.351],['CATB!H4',0,0,0],['CATC!H4',1,26.98,143.02],['CATC!H5',3,32.146,97.854],['CATC!H6',2,20.32,129.68],['CATD!H4',1,6.013,163.987],['CATD!H5',2,11.44,138.56]];
for(const [cell,attempt,seconds,expected] of excel)test('Excel reference '+cell,()=>assert.equal(schema.calculatePoints('EXCEL_2026',attempt,seconds,true),expected));
test('Zero, unsuccessful legacy and negative results stay distinct',()=>{assert.equal(schema.calculatePoints('EXCEL_2026',0,30,true),0);assert.equal(schema.calculatePoints('EXCEL_2026',4,140,true),-10);assert.equal(schema.calculatePoints('LEGACY_C',0,30,true),100);assert.equal(schema.calculatePoints('LEGACY_C',2,30,true),60);assert.equal(schema.calculatePoints('LEGACY_D',2,30,true),120);assert.equal(schema.calculatePoints('LEGACY_D',1,30,false),0);});
test('Comma decimals normalize; excess precision and missing values fail',()=>{const good={attempt:'1',seconds:'5,250',completed:'true',notes:''};assert.equal(schema.scoreSchema.parse(good).seconds,'5.250');for(const seconds of ['', '-1','NaN','1.0001','1e4'])assert(!schema.scoreSchema.safeParse({...good,seconds}).success);});
function scoreAction(denied=false){let calls=[];const action=load('app/admin/eventos/[id]/puntuaciones/actions.ts',{'../../../../../lib/scoring/schema':schema,'../../../../../lib/auth/authorization':{requireAccess:async()=>{if(denied)throw Error('DENIED');}},'../../../../../lib/supabase/server':{createClient:async()=>({rpc:async(name,args)=>{calls.push({name,args});return {data:'ok',error:null};}})},'next/navigation':{redirect:()=>{throw Error('REDIRECT');}},'next/cache':{revalidatePath:()=>{}}});return {action,calls};}
const id='00000000-0000-4000-8000-000000000001';const form=(values)=>{const f=new FormData();for(const [k,v]of Object.entries(values))f.set(k,v);return f;};const good={attempt:'1',seconds:'5,250',completed:'true',notes:''};
test('Authorization runs before score write',async()=>{const f=scoreAction(true);await assert.rejects(f.action.saveScore(id,id,id,null,{},form(good)),/DENIED/);assert.equal(f.calls.length,0);});
test('A forged total or rule is never forwarded to the database',async()=>{const f=scoreAction();await assert.rejects(f.action.saveScore(id,id,id,null,{},form({...good,points:'99999',rule:'anything'})),/REDIRECT/);assert.equal(f.calls.length,1);assert.equal(f.calls[0].args.p_seconds,5.25);assert(!('points' in f.calls[0].args));assert(!('rule' in f.calls[0].args));});
test('Corrections need a reason; invalid seconds never reach RPC',async()=>{const f=scoreAction();assert((await f.action.saveScore(id,id,id,'2026-09-21T00:00:00Z',{},form(good))).errors.notes);assert((await f.action.saveScore(id,id,id,null,{},form({...good,seconds:''}))).errors.seconds);assert.equal(f.calls.length,0);});
