'use client';
import {useActionState,useEffect,useRef} from 'react';
import Link from 'next/link';
import {saveEvent} from './actions';
import {emptyValues,statusLabels,statuses,type EventValues,type EventState} from '../../../lib/events/schema';
import s from './events.module.css';
export function EventForm({id,version=null,initial=emptyValues}:{id:string;version?:string|null;initial?:EventValues}){
 const [state,action,pending]=useActionState<EventState,FormData>(saveEvent.bind(null,id,version),{});
 const notice=useRef<HTMLDivElement>(null);useEffect(()=>{if(state.message)notice.current?.focus();},[state]);
 const values=state.values??initial;
 function input(key:Exclude<keyof EventValues,'public'|'status'>,label:string,type='text',required=false,maxLength?:number){return <div className={s.field}><label htmlFor={key}>{label}{required?' *':''}</label><input id={key} name={key} type={type} required={required} maxLength={maxLength} min={type==='number'?1:undefined} step={type==='number'?1:undefined} defaultValue={values[key]} aria-invalid={Boolean(state.errors?.[key])} aria-describedby={state.errors?.[key]?`${key}-error`:undefined}/>{state.errors?.[key]&&<p className={s.fieldError} id={`${key}-error`}>{state.errors[key]?.[0]}</p>}</div>}
 return <form action={action} noValidate aria-busy={pending}>
  {state.message&&<div ref={notice} tabIndex={-1} role="alert" className={s.error}>{state.message}</div>}
  <fieldset disabled={pending} className={s.formFields}><section className={s.card}><h2>01 · Información del evento</h2><p className={s.muted}>Los campos con * son obligatorios.</p>{input('name','Nombre del evento','text',true,150)}<div className={s.field}><label htmlFor="description">Descripción</label><textarea id="description" name="description" rows={4} maxLength={5000} defaultValue={values.description} aria-invalid={Boolean(state.errors?.description)} aria-describedby={state.errors?.description?'description-error':undefined}/>{state.errors?.description&&<p id="description-error" className={s.fieldError}>{state.errors.description[0]}</p>}</div>{input('organizer_name','Organizador','text',false,200)}</section>
  <section className={s.card}><h2>02 · Fechas del evento</h2><p className={s.muted}>Hora de Colombia (UTC−5). Define cuándo empieza y termina la competencia.</p><div className={s.grid}>{input('start_date','Inicio del evento','datetime-local',true)}{input('end_date','Fin del evento','datetime-local',true)}</div></section>
  <section className={s.card}><h2>03 · Lugar y capacidad</h2><div className={s.grid}>{input('location','Lugar','text',false,200)}{input('city','Ciudad','text',false,150)}{input('address','Dirección','text',false,300)}{input('max_teams','Máximo de equipos','number')}</div><p className={s.muted}>Déjalo vacío si aún no has definido una capacidad.</p></section>
  <section className={s.card}><h2>04 · Estado y recursos</h2><div className={s.field}><label htmlFor="status">Estado *</label><select id="status" name="status" defaultValue={values.status} aria-invalid={Boolean(state.errors?.status)} aria-describedby="status-help">{statuses.map(status=><option key={status} value={status}>{statusLabels[status]}</option>)}</select><p id="status-help" className={s.muted}>Para retirar un evento, elige Cancelado y guarda. Su información se conserva; puedes reactivarlo cambiando el estado.</p>{state.errors?.status&&<p className={s.fieldError}>{state.errors.status[0]}</p>}</div><label className={s.checkbox}><input type="checkbox" name="public" defaultChecked={values.public}/> Marcar como evento público</label><p className={s.muted}>Guarda tu intención de publicación. La ficha pública se habilitará en una fase posterior.</p><div className={s.grid}>{input('logo_url','Enlace al logo (opcional)','url',false,2000)}{input('rules_url','Enlace al reglamento (opcional)','url',false,2000)}</div><p className={s.muted}>Usa enlaces http:// o https:// a archivos ya alojados. No se suben archivos en esta fase.</p></section>
  <div className={s.actions}><Link href="/admin/eventos" className={s.secondary}>Volver al listado</Link><button className={s.primary} type="submit" disabled={pending}>{pending?'Guardando…':version?'Guardar cambios':'Crear evento'}</button></div>
  </fieldset>
 </form>;
}
