'use client';
import {useActionState} from 'react';
import {configureScoring} from './actions';
import {ruleLabels,type Board,type FormState} from '../../../../../lib/scoring/schema';
import s from '../../events.module.css';
export function ConfigForm({eventId,categoryId,config,hasScores,hardLocked}:{eventId:string;categoryId:string;config:Board['config'];hasScores:boolean;hardLocked:boolean}){
 const [state,action,pending]=useActionState<FormState,FormData>(configureScoring.bind(null,eventId,categoryId),{});
 return <form action={action} aria-busy={pending}><section className={s.card}><h2>Regla de puntuación</h2>{state.message&&<p role="alert" className={s.error}>{state.message}</p>}<p className={s.muted}>Elige la hoja de referencia. CATA tiene 4 retos; CATB, CATC y CATD tienen 3. La regla queda fija al guardar la primera puntuación; el número de retos puede aumentarse después (no puede bajar de uno que ya tenga puntuaciones).</p><fieldset className={s.formFields} disabled={pending||hardLocked}><div className={s.grid}><div className={s.field}><label htmlFor="rule">Fórmula del Excel</label><select name="rule" id="rule" required disabled={pending||hardLocked||hasScores} defaultValue={state.values?.rule??config?.rule??''}><option value="">Selecciona la regla</option>{Object.entries(ruleLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div className={s.field}><label htmlFor="count">Número de retos</label><input type="number" name="count" id="count" min={1} max={20} required defaultValue={state.values?.count??config?.challenge_count??3}/></div></div><p className={s.muted}>Se resta el tiempo total en segundos. CATA–CATD da 0 puntos con intento 0. Las reglas antiguas usan además “Reto logrado”; con intento 0 y reto logrado aplican la base 130. Se conservan los valores negativos del Excel.</p><button className={s.primary} disabled={pending||hardLocked}>{pending?'Guardando…':config?'Actualizar configuración':'Configurar retos'}</button></fieldset>{hardLocked&&<p className={s.muted}>Configuración bloqueada: el evento o la categoría están cerrados.</p>}{!hardLocked&&hasScores&&<p className={s.muted}>Ya hay puntuaciones: la fórmula quedó fija, pero puedes aumentar el número de retos.</p>}</section></form>;
}
